pubspec.yaml
Fill out the pubspec.yaml in preparation for publishing to pub.
- n/a
- n/a
=> CP-570 Add authors, documentation, homepage to pubspec

pubspec.yaml
=> CP-571 Add client platform team to authors

.travis.yml, README.md, tool/test.sh
- Setup Travis CI
**Source:**
- Add a `.travis.yml`
**Tests:**
- n/a
- n/a
- Travis CI successfully runs and passes on this branch
=> CP-572 Travis CI

LICENSE
- The LICENSE and NOTICE files are currently inconsistent in their spacing.
**Source:**
- Update the NOTICE to be consistent with LICENSE.
**Tests:**
- n/a
- n/a
- Travis-ci passes.
=> CP-587 Ensure license texts are consistent.

.travis.yml, lib/fluri.dart, pubspec.yaml, test/fluri_test.dart, tool/dartfmt.sh, tool/test.sh
- Dart code needs to be run through dartfmt to ensure consistent and clean code
- Ran `dartfmt` on code
- Added `tool/dartfmt.sh` script
- Travis should pass
- Running `./tool/dartfmt.sh` locally should not produce any changes to the code
@trentgrover-wf 
=> CP-597 fluri Dartfmt

README.md
- Add pub padge
**Source:**
- Add pub badge from shields.io to README
**Tests:**
- n/a
- n/a
- Pub badge displays latest pub release version and links to the pub package page for Fluri.
=> CP-602 Add Pub badge

CHANGELOG.md
- #16 
- We need a changelog file, especially since it's displayed on pub.dartlang.org
> Documentation only change
- Added `CHANGELOG.md`
@jayudey-wf 
---
Don't merge this yet. I will keep this open until we're ready for the next release, at which point I'll finalize updates and get one last round of reviews. After that's merged and the release is cut, I'll reopen and repeat the process.
=> CP-665 Add changelog

pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-574
JIRA and PR's included in this release: 
CP-583  - Fix fluri documentation generation  - https://github.com/Workiva/fluri/pull/9
CP-587  - Ensure license texts are consistent.  - https://github.com/Workiva/fluri/pull/10
CP-597  - fluri Dartfmt  - https://github.com/Workiva/fluri/pull/11
CP-602  - Add Pub badge  - https://github.com/Workiva/fluri/pull/12
CP-642  - Point travis-ci badge to master  - https://github.com/Workiva/fluri/pull/13
CP-657  - Setup code coverage through codecov.io  - https://github.com/Workiva/fluri/pull/14
CP-662  - Use dartanalyzer, fluri  - https://github.com/Workiva/fluri/pull/17
CP-665  - Add changelog  - https://github.com/Workiva/fluri/pull/19
Diff Between Last Tag and Proposed Release: …
=> CP-574 Release fluri 1.0.1

lib/fluri.dart, pubspec.yaml
- #22: There's a small bug in one of the documentation examples.
- #21: The team email is wrong.
**Source:**
- Fix bug in doc example.
- Update team email to clientplatform@workiva.com
**Tests:**
- n/a
- n/a
- CI build passes.
=> CP-687 Small fixes, fluri

.travis.yml, tool/dartfmt.sh
- #26 
- Updated `dartfmt.sh` script
- Added to CI build
- n/a
- CI build passes.
=> CP-697 Add dartfmt check to CI build, fluri.

README.md
#35 
Add dev section to readme. Points to dart_dev.
n/a
n/a
@jayudey-wf
=> CP-908 Add "development" section to readme.

README.md
#37 
Move badges to new line. **Docs only change.**
n/a
n/a
@jayudey-wf
=> CP-932 Move badges to separate line, fluri

CHANGELOG.md
**DOCS ONLY CHANGE**
Update changelog with new methods/constructors from #40 
@jayudey-wf
=> CP-1155 Update changelog with new methods/constructors

CHANGELOG.md
- Incorrect version in changelog for the next release, should be 1.1.0 according to semver
- Changed 1.0.2 to 1.1.0 in changelog
- n/a
- n/a
@jayudey-wf
=> CP-666 Update next release version, fluri 1.1.0

pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-666
JIRA and PR's included in this release: 
CP-687  - Small fixes, fluri  - https://github.com/Workiva/fluri/pull/24
CP-697  - Add dartfmt check to CI build, fluri.  - https://github.com/Workiva/fluri/pull/27
CP-704  - Update docs to use "fluri" var name  - https://github.com/Workiva/fluri/pull/29
CP-816  - Update code coverage collection and reporting  - https://github.com/Workiva/fluri/pull/33
CP-882  - Utilize dart_dev for tooling, fluri  - https://github.com/Workiva/fluri/pull/34
CP-1153  - Improvements/additions appendToPath, addPathSegment, setQueryParam, from ctor, fromUri ctor  - https://github.com/Workiva/fluri/pull/40
CP-1155  - Update changelog with new methods/constructors  - https://github.com/Workiva/fluri/pull/41
CP-1170  - …
=> CP-666 Release fluri 1.1.0

CHANGELOG.md
#44
doc-only change
@evanweible-wf 
FYI @jayudey-wf
=> CP-1242 Fix changelog formatting issue, fluri

pubspec.yaml
- [CP-1772 Analyzer: enable strong mode and linter.](https://github.com/Workiva/fluri/pull/52)
- [CP-2817 Support multi-value parameters](https://github.com/Workiva/fluri/pull/53)
Requested by: evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.1.1...version-bump-fluri-1-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.1.1...1.2.0
=> CP-1246 Release fluri 1.2.0

smithy.yaml
Need a smithy.yaml for RM dependency tracking.
@Workiva/client-platform-pp
=> CP-2924 Add smithy.yaml for dependency tracking

pubspec.yaml
* [CP-2919, CP-1901 Bugfix: calling .appendToPath() can result in duplicate slashes in URI](https://github.com/Workiva/fluri/pull/55)
* [CP-2925 Documentation updates, add GH templates](https://github.com/Workiva/fluri/pull/56)
* [CP-2924 Add smithy.yaml for dependency tracking](https://github.com/Workiva/fluri/pull/57)
Requested by: @charliekump-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.2.0...version-bump-fluri-1-2-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.2.0...1.2.1
=> CP-2918 Release fluri 1.2.1

docs.yml
We would like this readme in the dev portal
Added docs.yml
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
@Workiva/devtools-pp
=> WP-3657 : added docs.yml

pubspec.yaml, smithy.yaml
1. Some of the dev need updated ranges to facilitate strong-mode consumption / DDC compilation.
1. Update misc. dependencies to align with strong-mode / DDC compilation goals for the platform.
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
=> WP-4596 Update dependency ranges

pubspec.yaml
* [WP-4489 - Resolve dart_dev deprecation](https://github.com/Workiva/fluri/pull/65)
* [WP-4596 Update dependency ranges](https://github.com/Workiva/fluri/pull/66)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.2.2...version-bump-fluri-1-2-3
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.2.2...1.2.3
=> WP-4424 Release fluri 1.2.3

CODEOWNERS
Add a `CODEOWNERS` file so that we can turn on the "require reviews from codeowners" option.
@Workiva/app-frameworks
=> WP-5625 Add CODEOWNERS file

pubspec.yaml
* [WP-5625 Add CODEOWNERS file](https://github.com/Workiva/fluri/pull/69)
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/fluri/pull/70)
* [WP-6449 Dart 2 and DDC compatibility changes.](https://github.com/Workiva/fluri/pull/71)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.2.3...Workiva:release_fluri_1_2_4
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.2.3...1.2.4
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4676368400908288/logs/)
=> WP-4648 Release fluri 1.2.4

CHANGELOG.md, skynet.yaml
Rosie would like us to have a skynet.yaml.
Added a skynet.yaml to run the unit tests.
Add a skynet.yaml to run the unit tests.
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._
Please review: 
While we perform many automated checks before auto-merging, some manual checks are needed:
[contributing-review-types]: https://github.com/Workiva/fluri/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/fluri/blob/master/CONTRIBUTING.md#manual-testing-criteria
=> FEA-313: Create a basic skynet.yaml
