- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-573
JIRA and PR's included in this release: 
CP-572  - fluri Travis CI commit  - https://github.com/Workiva/fluri/pull/7
CP-571  - Add client platform team to authors  - https://github.com/Workiva/fluri/pull/6
CP-570  - Add authors, documentation, homepage to pubspec  - https://github.com/Workiva/fluri/pull/5
CP-568  - Update Apache 2.0 License  - https://github.com/Workiva/fluri/pull/4
CP-567  - fluri Licenses  - https://github.com/Workiva/fluri/pull/2
CP-566  - Fluent URI library (fluri)  - https://github.com/Workiva/fluri/pull/1
Diff Between Last Tag and Proposed Release: N/A
> CP-573 Release fluri 1.0.0

- pubspec.yaml
- The `documentation:` field must be completely left out in order to trigger the automatic doc generation when publishing to pub.
- Remove the `documentation:` field from `pubspec.yaml`
- Travis-CI passes
@trentgrover-wf 
> CP-583 Fix fluri documentation generation

- README.md
- Travis-CI badge was pointing to an old branch.
- Updated Travis-CI badge in readme to point to master.
- n/a
- Travis-CI badge displays a successful build and the image url has `?branch=master` at the end.
@jayudey-wf
> CP-642 Point travis-ci badge to master

- .gitignore
- .travis.yml
- README.md
- pubspec.yaml
- tool/coverage.sh
- tool/test.sh
- We need to report and display our code coverage.
**Source:**
- n/a
**Tools:**
- Coverage tools updated
- travis.yml updated to run and report coverage to codecov.io
**Tests:**
- n/a
**Other:**
- Readme updated to include code coverage badge (will only work once this is merged into master)
- n/a
- Coverage badge should be visible on README (will report "unknown" coverage until merged)
- Travis-ci should pass and this output should be visible in the logs towards the bottom:
```
The command "pub run dart_codecov_generator --report-on=lib/ --no-html --verbose" exited with 0.
pub run dart_codecov coverage.lcov
Running dart_codecov...
Coverage sent to codecov.io successfully.
```
@jayudey-wf
> CP-657 Setup code coverage through codecov.io

- .travis.yml
- lib/fluri.dart
- tool/analyze.sh
- We're not using dartanalyzer
**Source:**
- n/a
**Tests:**
- n/a
**Tools:**
- Added a `analyze.sh` tool that runs the dartanalyzer
- n/a
- Travis-CI passes and the dartanalyzer output can be found at the end of the build logs
```
$ ./tool/analyze.sh
Analyzing [lib/fluri.dart, test/fluri_test.dart]...
No issues found
No issues found
```
> CP-662 Use dartanalyzer, fluri

- README.md
- lib/fluri.dart
- To avoid confusion, we should recommend using "fluri" as the var name for `Fluri` instances.
- Discussion can be seen in #28.
_Doc changes only_
- Updated docs/examples to use "fluri" as var name for `Fluri` instances.
- n/a
- n/a
> CP-704 Update docs to use "fluri" var name

- .travis.yml
- pubspec.yaml
- We need to confirm that code coverage still works with latest Dart SDK
- We are currently not reporting code coverage to codecov.io
**Source:**
- None
**Tests:**
- None
**Tools:**
- Update versions of `coverage` package and coverage generation tool (https://github.com/codecov/dart)
- Utilize codecov's bash coverage reporter (https://github.com/codecov/codecov-bash) to report coverage on CI builds
- n/a
- Travis CI marks this PR as passing checks (requires passing build)
- Codecov.io marks this PR as passing checks (requires 100% coverage)
fyi: @jayudey-wf
> CP-816 Update code coverage collection and reporting

- .gitignore
- README.md
- lib/fluri.dart
- pubspec.yaml
- test/fluri_test.dart
- @oliverjanik suggested we add `addPathSegment()` and `setQueryParam()` (#39)
- missing some easy convenience constructors (from another `Fluri` instance, from a `Uri` instance)
**Source:**
- Add `.from()` constructor for constructing from other `Fluri` instances
- Add `.fromUri()` constructor for constructing from `Uri` instances
- Add `.appendToPath()` for adding a path literal to the end of the current path
- Add `.addPathSegment()` for adding a single path segment to the end of the current path
- Add `.setQueryParam()` for setting a single parameter and value without having to use a map
**Tests:**
- Tests for all of these have been added
- n/a
- CI passes
@jayudey-wf
> CP-1153 Improvements/additions: appendToPath(), addPathSegment(), setQueryParam(), from() ctor, fromUri() ctor

- lib/fluri.dart
- test/fluri_test.dart
- When using a class that mixes in `FluriMixin`, setting `.uri = null` will cause all other fluri methods to fail with a `NoSuchMethodError` on a null receiver.
**Source:**
- When setting the `uri` field, fallback to an empty URI (`Uri.parse('')`) if the given value is `null`.
**Tests:**
- Add a test ensuring the `FluriMixin` supports this scenario.
- Setting the full URI on a `FluriMixin` instance (covered by test)
- CI passes.
@jayudey-wf
> CP-1244 Default to empty URI when uri set to null

- CHANGELOG.md
**Docs only change.**
Adds the null URI bugfix from #48 to the changelog.
@jayudey-wf
> CP-1245 Changelog: null uri bugfix

- pubspec.yaml
JIRA: https://jira.webfilings.com/browse/CP-1176
JIRA and PR's included in this release: 
CP-1228  - cleanup old scripts, fluri  - https://github.com/Workiva/fluri/pull/46
CP-1242  - Fix changelog formatting issue, fluri  - https://github.com/Workiva/fluri/pull/47
CP-1244  - Default to empty URI when uri set to null  - https://github.com/Workiva/fluri/pull/48
CP-1245  - Changelog: null uri bugfix  - https://github.com/Workiva/fluri/pull/49
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.1.0...CP-1176_release_1.1.1
> CP-1176 Release fluri 1.1.1

- .analysis_options
- lib/fluri.dart
- test/fluri_test.dart
- tool/dev.dart
We should leverage the analyzer's strong mode and linter.
- Enable strong-mode and linter via `.analysis-options`
- Fix analyzer warnings, hints, and lints.
- CI passes.
> There will be 9 lints about documenting all public members:
> ```
> [lint] Document all public members (/Users/evanweible/dev/workiva/cp/fluri/lib/fluri.dart, line 146, col 7)
> ```
> This is because it conflicts with the preference for documenting only the getter when both a getter and setter exist. This is documented here and will be fixed: https://github.com/dart-lang/linter/issues/237
@trentgrover-wf 
@dustinlessard-wf 
@sebastianmalysa-wf 
@jayudey-wf
> CP-1772 Analyzer: enable strong mode and linter.

- CHANGELOG.md
- README.md
- lib/fluri.dart
- pubspec.yaml
- test/fluri_test.dart
Fixes #3.
Dart added a `Map<String, List<String>> queryParametersAll` field to the `Uri` class in 1.15.0. With that, we can provide better support for multi-value params. Currently the only way to set a query param to multiple values is to use the `set query(String query)` setter to do it manually.
This PR adds support for multi-value parameters:
- Expose a `Map<String, List<String>> queryParametersAll` getter for parity with `Uri`
- Expose a `queryParametersAll(Map<String, List<String>> queryParameters)` setter to allow an easy way to set the entire query with support for multi-value parameters.
- Update `setQueryParam` to accept either `String` or `Iterable<String>` for the value.
- Update `updateQuery` to accept either `String` or `Iterable<String>` for any of the values.
- Add a `bool …
> CP-2817 Support multi-value parameters

- lib/fluri.dart
- test/fluri_test.dart
Calling `.appendToPath()` can result in duplicate slashes in URI if the `path` is set with a trailing slash and `.appendToPath()` is called with a leading slash.
**Source:**
* Check the existing path for a trailing slash, if it has one check the path given to `.appendToPath()` and remove a leading slash if it is there.
**Tests:**
* Add a test for this scenario.
- CI Passes
@Workiva/client-platform-pp
> CP-2919, CP-1901 Bugfix: calling .appendToPath() can result in duplicate slashes in URI

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Use release notes instead of changelog (link to releases page from changelog)
- Add versioning and stability commitment to readme
- Add GitHub issue template
- Add GitHub pull request template
- Add GitHub contributing guidelines
Also - shout out to the UIP team, I borrowed most of the contributing guidelines from their repos.
---
**Docs only change.**
@trentgrover-wf 
@dustinlessard-wf 
@jayudey-wf 
@sebastianmalysa-wf
> CP-2925 Documentation updates, add GH templates

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
The @Workiva/client-platform-pp alias is restricted to the Workiva org, and thus can't be tagged by external users.
Use our individual usernames in the Issue and PR templates.
@Workiva/client-platform-pp
> CP-2928 Use individual username tags instead of group alias

- .analysis_options
The recommended lint rules are not set in analysis options
Added
- cancel_subscriptions
- close_sinks
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
> WP-4420 Add recommended lint rules

- pubspec.yaml
* [WP-3657 : added docs.yml](https://github.com/Workiva/fluri/pull/61)
* [WP-4420 Add recommended lint rules](https://github.com/Workiva/fluri/pull/63)
* [CP-2928 Use individual username tags instead of group alias](https://github.com/Workiva/fluri/pull/60)
Requested by: @maxpeterson-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.2.1...version-bump-fluri-1-2-2
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.2.1...1.2.2
> WP-2927 Release fluri 1.2.2

- pubspec.yaml
- tool/dev.dart
- performed memory audit and found nothing relevant
- dart_dev deprecated directories and replaced with paths, so I made the change here and upgraded the min ddev dependency
@dustinlessard-wf @evanweible-wf @jayudey-wf @maxwellpeterson-wf @sebastianmalysa-wf @trentgrover-wf
> WP-4489 - Resolve dart_dev deprecation

- CHANGELOG.md
- pubspec.yaml
Pull Requests included in release:
* [update build](https://github.com/Workiva/fluri/pull/73)
* [AF-2471 Dart 2](https://github.com/Workiva/fluri/pull/74)
Requested by: @evanweible-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/fluri/compare/1.2.4...Workiva:release_1.2.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/fluri/compare/1.2.4...1.2.5
The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4676368400908288/logs/)
> WP-6452 Release fluri 1.2.5

- .gitignore
- .travis.yml
- Dockerfile
- lib/fluri.dart
- validate.sh
We are getting ready to ship Dart2 code to production.Since we compile that code with dart2js, it would be great to run unit tests with dart2js as well. This will provide more confidence in the shipped code.
- Update `.gitignore`
- dart2 format
- Use `dart2.5`
- Use pub2 solver in Dockerfile
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._
Please review: 
While we perform many automated checks before auto-merging, some manual checks are needed:
[contributing-review-types]: https://github.com/Workiva/fluri/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/fluri/blob/master/CONTRIBUTING.md#manual-testing-criteria
> CPLAT-7482: Run unit tests with dart2js

- CHANGELOG.md
- README.md
- pubspec.yaml
- Remove the coverage link since it was broken and we're no longer reporting coverage in CI.
- Update the pub links to the new `pub.dev` domain
- Remove the ToC since the last PR removed a couple of the sections and it's no longer necessary
> CPLAT-7938: Remove broken link and unnecessary ToC

- .travis.yml
- CHANGELOG.md
- Dockerfile
- LICENSE
- NOTICE
- README.md
- lib/fluri.dart
- pubspec.yaml
- test/fluri_test.dart
Add a way to remove query param(s) from a URI:
```dart
Fluri('https://example.com/?foo')
..removeQueryParam('foo');
```
> CPLAT-11688: Add a `removeQueryParam` method.

- docs.yml
https://jira.atl.workiva.net/browse/DE-552
As part of, 
[Dev Portal Service deprecation](https://wiki.atl.workiva.net/display/DE/Poster+-+Dev+Portal+Discovery+2.0%3A+Discovery+and+Planning); 
we are deprecating the “docs.yml” file that’s been created to render repo markdown files on to the portal.
File paths included in docs.yml of this repo will no longer be rendered/hosted on
[Dev Portal](https://dev.workiva.net/docs/) with the yml file deletion.
Please reach out to `#support-dev-portal` or `#support-developer-efficiency` with any questions.
[_Created by Sourcegraph batch change `Workiva/remove_docs_yml`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/remove_docs_yml)
> DE-638: Delete docs.yml file created for Dev Portal.

- .github/PULL_REQUEST_TEMPLATE.md
This batch changes references to the archived support-client-plat slack channel to now reference the support-frontend-architecture channel.
`replace "#support-client-plat" "#support-frontend-architecture"`
CI passing should be sufficient as these changes are documentation changes.
[_Created by Sourcegraph batch change `Workiva/update_slack_channel_fea`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/update_slack_channel_fea)
> Update references to the archived slack room #support-client-plat

- skynet.yaml
Currently the skynet config is running on pull requests as well as releases which is causing us to hit the github api rate limit, we don't really need to have the skynet config running on pull requests because it's just needed for release pipelines. 
Add a run config to skynet that limits running to just releases and if there are changes to the skynet.yaml
Run skynet only on releases
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._
Please review: 
While we perform many automated checks before auto-merging, some manual checks are needed:
[contributing-review-types]: https://github.com/Workiva/fluri/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: …
> FW-166 Only run skynet on releases

- pubspec.yaml
Pull Requests included in release:
* Patch changes:
* [FW-147 Change skynet config to check that github workflow passes](https://github.com/Workiva/fluri/pull/94)
* [FW-166 Only run skynet on releases](https://github.com/Workiva/fluri/pull/95)
* [Update to latest image of github ci verifier](https://github.com/Workiva/fluri/pull/96)
* [Update references to the previous team name](https://github.com/Workiva/fluri/pull/97)
* [FEDX-688 GHA OSS changes](https://github.com/Workiva/fluri/pull/99)
* [FEDX-1716: Workiva Analysis Options v2](https://github.com/Workiva/fluri/pull/100)
* [FEDX-1789: Migarte to gha-dart-oss](https://github.com/Workiva/fluri/pull/101)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/fluri/pull/102)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed …
> RM-146278 Release fluri 2.0.6
